server:
  port: 8081
spring:
  logging:
    level:
      com.keyrus.proxemconnector.connector.csv.configuration.rest.router: DEBUG
  application:
    name: proxemconnectordev
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  zipkin:
    baseUrl: http://localhost:9411/
logging:
  level:
    web: DEBUG
management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
      beans:
        enabled: true
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"
connectors:
  rest:
    error-header: error
