version: '3.1'
services:
  proxem_connector_postgresql_db:
    container_name: proxem_connector_postgresql_db
    image: postgres:15.2-alpine3.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
  proxem_connector_db_adminer:
    container_name: proxem_connector_db_adminer
    image: adminer:4.8.1-standalone
    ports:
      - "9180:8080"
  proxem_connector_app:
    container_name: proxem_connector_app
    image: proxemconnector.jar
    ports:
      - "8080:8080"


